server:
  port:
    8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VladimirPoddubchak/spring-cloud-config-store
          search-paths:
            - '*service'


